### ISSUE TITLE
В генерируемом XML для Signed_Order_B64 отсутствует нода merchant

### ISSUE THREAD

**Issue by panda-madness** [kolesa-team/qazkom-epay#2]
[Pastebin раскодированного XML.](https://pastebin.com/V4WHRVRP)

[Судя по документации](https://testpay.kkb.kz/doc/htm/xml_description.html) здесь должна быть нода merchant, и не должна быть нода xsl:stylesheet.

**Comment by iborodikhin** [comment]
Пожалуйста, предоставьте пример кода.

**Comment by panda-madness** [comment]
Закрыто в связи с реализацией собственной глупости.
