### ISSUE TITLE
epay integration

### ISSUE THREAD

**Issue by abubakr98-kji** [kolesa-team/qazkom-epay#8]
оплата проходит успешно , но ответ к нам не поступает .

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Epay</h4>
        </div>
        <div class="modal-body">
            <form name="SendOrder" method="post" action="https://testpay.kkb.kz/jsp/process/logon.jsp">
                <input type="hidden" name="Signed_Order_B64" value="{{$content}}">
                <label for="staticEmail" class="col-form-label">Email</label>
                <input class="form-control" type="text" name="email" size=50 maxlength=50 value="{{$_email}}">
                <p>
                    <input type="hidden" name="Language" value="rus">
                    
                    <input type="hidden" name="BackLink" value="">
                    
                    <input type="hidden" name="PostLink" value="postlink">
                    
                    <br>
                    {{-- <input type="submit" name="GotoPay" value="GotoPay">&nbsp; --}}
                    <div class="modal-footer">
                        <button type="submit" name="GotoPay" value="GotoPay" class="btn btn-custom pull-left">Send</button>
                    </div>
            </form>
        </div>

    </div>
</div>
------------------------
public function postLink(Request $request) {
    Log::info($request);

  }
--------------------
VerifyCsrfToken.php - мы отключили проверку токена с этого роута

**Comment by abubakr98-kji** [comment]
как нам это решить ?

**Comment by antonsergeyev** [comment]
Вопрос мало понятен, код примера разъехался.

Убедитесь, что при отправке формы в epay в ней указываете параметр PostLink со ссылкой на ваш проект. По этой ссылке к вам придёт ответ от epay. 
Если ссылка PostLink есть, но запрос туда не приходит - убедитесь, что этот адрес доступен из интернета. 
Можно включить access log в настройках вашего сервера и проверить, доходят ли запросы до него.

**Comment by abubakr98-kji** [comment]
Здравствуйте Антон.
Ответ об успешной оплате не приходит . Пожалуйста посмотрите , скажите в
чем может быть проблема?
[image: image.png]
-------------------------------------------------
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Epay</h4>
        </div>
        <div class="modal-body">
            <form name="SendOrder" method="post" action="
https://testpay.kkb.kz/jsp/process/logon.jsp">
                <input type="hidden" name="Signed_Order_B64"
value="{{$content}}">
                <label for="staticEmail"
class="col-form-label">Email</label>
                <input class="form-control" type="text" name="email"
size=50 maxlength=50 value="{{$_email}}">
                <p>
                    <input type="hidden" name="Language" value="rus">
                    
                    <input type="hidden" name="BackLink" value="
https://api.ustaz.xyz">
                    
                    <input type="hidden" name="PostLink" value="
https://api.ustaz.xyz/postLink">
                    
                    <br>
                    {{-- <input type="submit" name="GotoPay"
value="GotoPay">&nbsp; --}}
                    <div class="modal-footer">
                        <button type="submit" name="GotoPay"
value="GotoPay" class="btn btn-custom pull-left">Send</button>
                    </div>
            </form>
        </div>

    </div>
</div>
--------------
public function postLink(Request $request) {
    Log::info($request);

  }
-------------
Route::post('postLink', 'UserController@postLink');



















ср, 28 окт. 2020 г. в 12:15, Anton <notifications@github.com>:

**Comment by antonsergeyev** [comment]
Пример выглядит нормально, явных ошибок не вижу.
Думаю, стоит обратиться в техподдержку epay.

**Comment by abubakr98-kji** [comment]
Добрый день Антон. Простите за беспокойство , вы можете нам ответить , но
если у вас есть возможность уделите нам немного своего драгоценного времени
совет пожалуйста. Посмотрите пожалуйста файл, в файле мы через постман
отправляем запрос но нам не приходит ответ от банка об оплате , может быть
это ошибка нашего кода.

ср, 28 окт. 2020 г. в 13:33, Anton <notifications@github.com>:
